[build]
  functions = "netlify/functions"
  publish = "dist"

# Environment variables for the Netlify functions
# You'll need to set these in your Netlify dashboard: Site settings > Environment variables
# SECRET_SMTP_HOST
# SECRET_SMTP_USER
# SECRET_SMTP_PASSWORD
# SECRET_SMTP_PORT
# SECRET_SMTP_SSL

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
