import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'bg';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    'nav.home': 'Home',
    'nav.about': 'About us', 
    'nav.services': 'Solutions',
    'nav.contact': 'Contact',
    'nav.getInTouch': 'Get in touch',
    'hero.mainTitle': 'We aggregate data, automate processes',
    'hero.subtitle': 'and deliver real-time reports, optimal, scalable, and affordable analytical solutions.',
    'hero.businessTitle': 'For Business:',
    'hero.feature1': 'Real-time aggregated "data"',
    'hero.feature2': '"Automation" saving time and resources',
    'hero.feature3': 'Analytical "services"',
    'hero.feature4': 'In-house "developments"',
    'hero.feature5': '"Expertise" on data & domain knowledge',
    'hero.feature6': '"10+" PhDs & researchers in engineering, economics, and IT',
    'hero.learnMore': 'Learn more',
    'statistics.processAutomation': 'Degree of process automation',
    'statistics.businessCompanies': 'Business companies we work with',
    'statistics.analyticalProducts': 'Analytical products',
    'problems.title': 'Challenges We Solve',
    'problems.1.title': 'Out-of-date credit history',
    'problems.1.desc1': 'Delays in credit bureaus lead to risky lending and fraud.',
    'problems.1.feature1': 'We aggregate real-time data from financial companies and other sources',
    'problems.1.result': 'More approvals at a given risk thanks to up-to-date data',
    'problems.2.title': 'Limited Data → Limited Decisions',
    'problems.2.desc1': 'Internal models and strategies rely only on the company\'s customer data.',
    'problems.2.feature1': 'We provide external aggregated data and pool scores',
    'problems.2.result': 'More approvals at a given risk and fewer frauds, thanks to additional data',
    'problems.3.title': 'Insufficient approvals at a desired risk',
    'problems.3.desc1': 'High risk among approved and/or missed opportunities among rejected applicants.',
    'problems.3.feature1': 'We provide real-time aggregated data from multiple sources',
    'problems.3.feature2': 'Deliver generalized scores based on aggregated up-to-date data',
    'problems.3.result': 'More approvals at a given risk thanks to better-informed decisions',
    'problems.4.title': 'Not Taken Up',
    'problems.4.desc1': 'Slow approval or unsuitable credit terms.',
    'problems.4.feature1': 'Fast response with aggregated data and pool scores',
    'problems.4.feature2': 'Up/down sale based on data analysis and expertise',
    'problems.4.result': 'Higher conversion of approved applicants',
    'problems.5.title': 'Fraud risk',
    'problems.5.desc1': 'Fraud detection relies on the company\'s available data.',
    'problems.5.feature1': 'We use of up-to-date and external data',
    'problems.5.feature2': 'Detect the consistency of client data',
    'problems.5.result': 'Stronger fraud protection',
    'problems.6.title': 'Inefficient collection',
    'problems.6.desc1': 'Inefficient interaction with active clients.',
    'problems.6.feature1': 'We forecast active client behavior',
    'problems.6.feature2': 'Estimate ability to pay', 
    'problems.6.feature3': 'Optimize individual communication strategy',
    'problems.6.result': 'Optimized collection across all stages',
    'problems.7.title': 'Inefficient client acquisition',
    'problems.7.desc1': 'High customer acquisition cost. Missed or mistargeted clients.',
    'problems.7.feature1': 'The adaptive capability of our solution lead to a more accurate propensity prediction',
    'problems.7.result': 'More effective targeting and lower customer acquisition cost',
    'problems.8.title': 'Inefficient marketing campaigns',
    'problems.8.desc1': 'Non-optimal parameters of individual offers. Marketing not aligned with risk, budget, and other constraints.',
    'problems.8.feature1': 'We developed a system for optimizing individual offers',
    'problems.8.feature2': 'Adaptive features ensure up-to-date offers',
    'problems.8.feature3': 'Business constraints are accounted for',
    'problems.8.result': 'Optimal customers acquisition',
    'problems.9.title': 'Regulatory risk',
    'problems.9.desc1': 'Regulatory fines and penalties for non-compliance.',
    'problems.9.feature1': 'We provide scorings aligned with regulatory requirements',
    'problems.9.result': 'Avoidance of regulatory sanctions',
    'services.title': 'Our Solutions',
    'services.description': 'We provide analytical solutions (SOL) trained on aggregated or client-specific data, the response (RSP) of executed solutions, or a complete software product (ASF) for SOL development.',
    'services.rsp.title': 'RSP: Solution Response',
    'services.rsp.desc': 'score, forecast, recommendation, offer, and more, delivered in real time or on a daily basis, regularly updated, with continuous monitoring and support',
    'services.sol.title': 'SOL: Analytical Solution',
    'services.sol.desc': 'a system for generating RSP, consisting of modules for data preparation, segmentation, forecasting, calibration, recommendation and offer generation, and more. Delivered quarterly with transformed input variables available on demand, with continuous monitoring and support',
    'services.asf.title': 'ASF: Automated Solution Factory',
    'services.asf.desc': 'a complete software product for generating SOL, implemented on a project basis, with continuous monitoring and support',
    'services.filters.all': 'All',
    'services.filters.applicants': 'Applicants',
    'services.filters.activeClients': 'Active clients',
    'services.filters.inactiveClients': 'Inactive clients',
    'services.bureauScoring.title': 'Personal AUTEGRY Score (PAS)',
    'services.bureauScoring.desc': 'Reflects risky patterns in aggregated AUTEGRY data',
    'services.applicationScoring.title': 'Application',
    'services.applicationScoring.desc': 'Real-time risk insights',
    'services.fraudScoring.title': 'Fraud',
    'services.fraudScoring.desc': 'Detects fraud in real time using aggregated AUTEGRY data',
    'services.behavioralScoring.title': 'Active Behavior',
    'services.behavioralScoring.desc': 'Assessment the dynamic risk of active borrowers',
    'services.propensityScoring.title': 'Propensity',
    'services.propensityScoring.desc': 'Represents the likelihood an applicant to apply for credit',
    'services.churnScore.title': 'Churn',
    'services.churnScore.desc': 'Represents the probability of customer attrition',
    'services.collection.title': 'Dept Collection',
    'services.collection.desc': 'Estimating near-term default risk for delinquent customers',
    'services.recovery.title': 'Recovery',
    'services.recovery.desc': 'Reflects the risk of non-repayment from written-off / heavily overdue loans',
    'services.cashflow.title': 'Cashflow',
    'services.cashflow.desc': 'Revenue forecasts from contracts',
    'services.marketing.title': 'Marketing',
    'services.marketing.desc': 'Ongoing optimized marketing campaign - tailored to single or multiple objectives',
    'services.features.applicationScoring.1': 'Score 0-1000, calibrated, with standardized zones A1-E4',
    'services.features.applicationScoring.2': 'Key factors highlighted',
    'services.features.applicationScoring.3': 'Compliant with regulations',
    'services.features.applicationScoring.4': 'Quarterly models training & system calibration',
    'services.features.bureauScoring.1': 'Real-time risk insights',
    'services.features.bureauScoring.2': 'Generic score 0-1000, calibrated, with standardized zones A1-E4',
    'services.features.bureauScoring.3': 'Key positive & negative drivers',
    'services.features.bureauScoring.4': 'Compliant with regulations',
    'services.features.bureauScoring.5': 'Quarterly models training & system calibration',
    'services.features.fraudScoring.1': 'Trained on aggregated AUTEGRY data',
    'services.features.fraudScoring.2': 'Reflects predefined fraudulent behavior within the aggregated AUTEGRY data',
    'services.features.fraudScoring.3': 'Score 0-1000, calibrated, with standardized zones A-E',
    'services.features.fraudScoring.4': 'Quarterly models training & system calibration',
    'services.features.behavioral.1': 'Tracks dynamic performance shifts',
    'services.features.behavioral.2': 'Score 0-1000, calibrated, with standardized zones A1-E4',
    'services.features.behavioral.3': 'Quarterly models training & system calibration',
    'services.features.churn.1': 'Score 0-1000, calibrated, with standardized zones A1-E4',
    'services.features.churn.2': 'Quarterly models training & system calibration',
    'services.features.churn.3': '',
    'services.features.collection.1': 'Score 0-1000, calibrated, with standardized zones A1-E4',
    'services.features.collection.2': 'Quarterly models training & system calibration',
    'services.features.recovery.1': 'Score 0-1000, calibrated, with standardized zones A1-E4',
    'services.features.recovery.2': 'Quarterly models training & system calibration',
    'services.features.cashflow.1': 'Horizons: 1, 2, 3, 6, 12 months',
    'services.features.cashflow.2': 'Individual & aggregated levels',
    'services.features.cashflow.3': 'Quarterly models update',
    'services.features.marketing.1': 'Constraints integrated (risk, budget, offers frequency and more)',
    'services.features.marketing.2': 'Adaptation to current market behavior',
    'services.features.marketing.3': 'Individual-level optimization',
    'services.features.marketing.4': 'AI-based personalized offers',
    'services.features.marketing.5': 'Daily adaptation to customer behavior',
    'about.title': 'About us',
    'about.mission.title': 'Mission',
    'about.mission.desc': 'Automation and data for secure, efficient, and optimal management of your business.',
    'about.vision.title': 'Vision',
    'about.vision.desc': 'Sustainable and efficient business growth.',
    'about.whoWeAre.title': 'Who We Are',
    'about.whoWeAre.desc': 'We are a PhD team that combines experience in data science and IT with deep domain knowledge in finance, retail, marketing, and industrial process automation.',
    'insights.title': 'Insights',
    'footer.description': 'We aggregate data, automate processes, and deliver real-time reports as well as optimal, scalable, and affordable analytical solutions.',
    'footer.company': 'Company',
    'footer.services': 'Solutions',
    'footer.getInTouch': 'Get in touch',
    'footer.home': 'Home',
    'footer.aboutUs': 'About Us',
    'footer.solutions': 'Solutions',
    'footer.contact': 'Contact',
    'whyAutegry.title': 'Why AUTEGRY',
    'whyAutegry.subtitle': 'With us, you access aggregated data, analytical and technological solutions. Through our automation, you achieve optimal management of your business.',
    'whyAutegry.automation.title': 'Automation',
    'whyAutegry.automation.desc': 'Automation of data science, business, and industrial processes to achieve optimal, scalable, and cost-efficient results.',
    'whyAutegry.realTimeData.title': 'Data',
    'whyAutegry.realTimeData.desc': 'Data is an invaluable resource. We continuously work to expand and enrich the data we collect.',
    'whyAutegry.analytics.title': 'Analytics',
    'whyAutegry.analytics.desc': 'By combining a data-driven approach with domain expertise, we create comprehensive analytical solutions that automate processes.',
    'whyAutegry.technology.title': 'Technology',
    'whyAutegry.technology.desc': 'Technology is at the core of everything we do. The security of our systems is our highest priority, and their efficiency is the catalyst for our services and developments quality.',
    'cookieBanner.title': 'This website uses cookies',
    'cookieBanner.description': 'This site uses cookies to improve your experience. We use them to analyze traffic and personalize content specifically for you. By continuing to browse, you agree to our Cookie Policy',
    'cookieBanner.allowAll': 'Allow all cookies',
    'cookieBanner.necessary': 'Use necessary cookies only',
    'contact.title': 'Send us a message',
    'contact.name': 'Full name',
    'contact.namePlaceholder': 'Jane Doe',
    'contact.email': 'Work email',
    'contact.emailPlaceholder': 'example@domain.com',
    'contact.phone': 'Mobile phone',
    'contact.phonePlaceholder': '+359 ..',
    'contact.subject': 'SUBJECT',
    'contact.subjectPlaceholder': 'Enter subject',
    'contact.message': 'MESSAGE',
    'contact.messagePlaceholder': 'Please write your message',
    'contact.submit': 'Submit message',
    'contact.contactUs': 'CONTACT US',
    'contact.emailLabel': 'EMAIL',
    'contact.phoneLabel': 'PHONE',
    'contact.officeLabel': 'LOCATION',
    'contact.socialLabel': 'ON SOCIAL',
    'contact.officeAddress': 'Studentski grad, ul. "Rosario" 1, 1756 Sofia',
    'team.title': 'Our Team',
    'team.subtitle': 'Meet the experts who make our solutions possible',
    'team.connect': 'Connect',
    'services.loadMore': 'Load more',
    'services.showLess': 'Show less',
    'team.member1.name': 'Alexander Efremov',
    'team.member1.position': 'CEO & Founder',
    'team.member1.email': 'alexander.efremov@autegry.com',
    'team.member1.bio': '25+ years of experience in Data Science, automation, and applied AI across the chemical industry, satellite communications, retail, lending, marketing, and more. Associate Professor and Vice Dean for Business Relations at the Faculty of Automatics, TU–Sofia (courses in ML, DM, AI, Production Automation, etc.).',
    'team.member1.linkedin': 'linkedin.com/in/aefremov',
    'team.member2.name': 'Fani Tomova',
    'team.member2.position': 'Principal Database & DWH Architect',
    'team.member2.email': 'fani.tomova@autegry.com',
    'team.member2.bio': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.',
    'team.member2.linkedin': 'linkedin.com/in/lorem-ipsum',
    'team.member3.name': 'Radostin Merakov',
    'team.member3.position': 'Principal Platform Ops Architect',
    'team.member3.email': 'radostin.merakov@autegry.com',
    'team.member3.bio': 'Extensive experience in Python development, DevOps practices, and database architecture design. Skilled in building scalable systems with SQLAlchemy and Alembic, and leading platform operations that enable reliable, maintainable applications.',
    'team.member3.linkedin': 'linkedin.com/in/lorem-ipsum',
    'team.member4.name': 'Iveta Grigorova',
    'team.member4.position': 'Head of Analytical Solutions & Delivery',
    'team.member4.email': 'iveta.grigorova@autegry.com',
    'team.member4.bio': 'With extensive experience in Data Science, financial control, internal audit, and accounting. She is a PhD candidate at the Faculty of Automation, Technical University of Sofia, and teaches ML, DM, and AI courses at both TU Sofia and Paisii Hilendarski University in Plovdiv. She is responsible for the business side of developing and delivering RSP, SOL, and ASF solutions. She coordinates key processes, configures and administers ASF, analyzes reports, and monitors from a Data Science perspective. She also manages client communication, conducts business analyses and presents results at various company levels.',
    'team.member4.linkedin': 'linkedin.com/in/lorem-ipsum',
    'team.member5.name': 'Alexander Karamfilov',
    'team.member5.position': 'Head of Strategic Projects',
    'team.member5.email': 'alexander.karamfilov@autegry.com',
    'team.member5.bio': 'Leads the technical development of ASF systems, coordinates Data Science teams, facilitates effective client communication, presents business analysis and results, and organizes solution integration in collaboration with various teams. Monitors project execution, resolves technical and organizational challenges, and ensures high-quality delivery of products in accordance with requirements.',
    'team.member5.linkedin': 'linkedin.com/in/lorem-ipsum',
    'team.member6.name': 'Nelina Nedelcheva',
    'team.member6.position': 'Head of Design & Marketing',
    'team.member6.email': 'nelina.nedelcheva@autegry.com',
    'team.member6.bio': 'Manages the overall visual identity and marketing campaigns, develops effective design strategies, coordinates teams, and analyzes market trends to optimize the brand. Graduated in Design and Print Communications from Technical University - Sofia, Plovdiv campus.',
    'team.member6.linkedin': 'linkedin.com/in/lorem-ipsum',
    'legal.title': 'Legal Information',
    'legal.subtitle': 'Important information about our terms, privacy practices, and cookie usage',
    'legal.terms.title': 'Terms & Conditions',
    'legal.terms.intro': 'Our company – Autegry Ltd., registered in the Bulgarian Commercial Register at the Registry Agency, with UIC: 206957397, with headquarters and registered address: Republic of Bulgaria, Sofia, 1756, Studentski grad Residential Area, Rosario St. 1, phone: +359 89 999 9999, email: info@autegry.com. These General Terms and Conditions govern the use of www.autegry.com. By using the website, the user agrees to these General Terms and Conditions. If you do not agree with them, you should refrain from using the website.',
    'legal.terms.section1.title': '1. Intellectual Property',
    'legal.terms.section1.p1': '1.1 All rights concerning intellectual property related to the informational resources and content of the website are exercised by the Operator. They are protected by the Copyright and Related Rights Act, and any use of the website\'s content without the Operator\'s consent constitutes a violation of the law, which may result in civil, administrative, or criminal liability.',
    'legal.terms.section1.p2': '1.2 In the event of copying or reproducing information beyond what is permitted, as well as any other infringement of the Operator\'s intellectual property rights, the Operator reserves the right to claim compensation for all direct and indirect damages incurred.',
    'legal.terms.section2.title': '2. Limitation of Liability',
    'legal.terms.section2.p1': '2.1 The Operator takes necessary measures to keep the website content up-to-date, but does not guarantee its actual accuracy. Accordingly, the Operator is not liable for damages, including direct or indirect damages, or lost profits sustained by a user under any circumstances related to the published content or access to the website. By using the website, users assume all risks associated with it, including risks to end-user devices, software, or user data.',
    'legal.terms.section2.p2': '2.2 If the website contains links to content located outside the website, the user acknowledges that the Operator has no control over such content and bears no responsibility for consequences arising from activating external links. The Operator is not responsible for any malicious actions by third parties that the user may be subject to when using the website. Use of the website is at the user\'s own risk.',
    'legal.terms.section3.title': '3. User Registration',
    'legal.terms.section3.p1': '3.1 The Operator reserves the right to provide certain website content exclusively to users who have registered a user profile on the website. Such content, restricted to registered users only, will be clearly marked as such by the Operator at all times.',
    'legal.terms.section3.p2': '3.2 By creating a user profile, the user agrees that the Operator may process their personal data in accordance with the Privacy Policy published on the website.',
    'legal.terms.section4.title': '4. Use of the Website',
    'legal.terms.section4.p1': '4.1 If the Operator allows users to upload content to the website, users must not upload defamatory, obscene, offensive, pornographic, illegal, or otherwise immoral content.',
    'legal.terms.section4.p2': '4.2 Users must act in good faith in their use of the website and must not engage in malicious actions that could affect content accessibility for others or the overall operation of the website.',
    'legal.terms.section5.title': '5. Miscellaneous',
    'legal.terms.section5.p1': '5.1 The Operator reserves the right to modify these General Terms and Conditions at its discretion. The current terms of use for the website will be published at all times on the website.',
    'legal.terms.section5.p2': '5.2 Any matters not regulated herein shall be governed by the applicable legislation of the Republic of Bulgaria.',
    'legal.privacy.title': 'Privacy Policy',
    'legal.privacy.subtitle': 'We Care About Your Personal Data',
    'legal.privacy.intro': 'Information About the Data Controller\nAutegry Ltd. is a company registered in the Commercial Register of the Registry Agency with UIC: 206957397, email: info@autegry.com, phone: +359 89 999 9999.',
    'legal.privacy.section1.title': '1. Grounds and Purposes for Processing Your Personal Data',
    'legal.privacy.section1.intro': 'We process your personal data on the following grounds:\n- The General Terms and Conditions for using the website;\n- Your explicit consent – the specific purpose will be indicated for each case;\n- Legal obligation.\n\nDetailed information about the processing of your personal data based on the applicable grounds is provided below.',
    'legal.privacy.section1.1.title': '1.1 Performance of Contract',
    'legal.privacy.section1.1.content': 'We process your personal data for the purposes of website use in accordance with the General Terms and Conditions.\nPurposes of processing (where applicable):\n- Verification of your identity;\n- Providing the functionalities of our website;\n\nOn this basis, we only process personal data provided in connection with submitted inquiries via the contact form, including company BULSTAT number, first and last name, phone, and email address. Data collected on this basis will be deleted 2 years after termination of the contractual relationship, regardless of reason.',
    'legal.privacy.section1.2.title': '1.2 With Your Consent',
    'legal.privacy.section1.2.content': 'We process your personal data on this basis only after your explicit, unambiguous, and voluntary consent. There will be no adverse consequences if you refuse data processing.\nConsent constitutes a separate legal basis for processing, with the purpose specified in it and distinct from purposes listed in this policy. If you provide consent, until you withdraw it or terminate any contractual relationship with us, we may prepare appropriate product/service offers tailored for you by analyzing your core personal data.\nData processed on this basis:\nPersonal data used for direct marketing purposes, including website usage data and social media profile data.\nDisclosure to Third Parties:\nWe may share your data with marketing agencies, Facebook, Google, or similar entities on this basis.\n\nWithdrawal of Consent\nConsents given may be withdrawn at any time without affecting contract performance. If you withdraw consent for any or all processing purposes above, we will cease using your personal data for those purposes. Withdrawal does not affect the lawfulness of processing based on consent prior to withdrawal. To withdraw consent, simply use our website or contact us.\nData collected under this basis will be deleted upon your request or 12 months after initial collection.',
    'legal.privacy.section2.title': '2. How We Protect Your Personal Data',
    'legal.privacy.section2.content': 'To ensure adequate protection of company and client data, we implement all required organizational and technical measures as stipulated by the Personal Data Protection Act. We have established rules to prevent data breaches and misuse, supporting secure processing and safeguarding of your data. For maximum security during processing, transfer, and storage, we may use additional protection mechanisms such as encryption and pseudonymization.',
    'legal.privacy.section3.title': '3. Users\' Rights',
    'legal.privacy.section3.intro': 'Every website user has the rights guaranteed under Bulgarian and EU data protection laws. Users may exercise their rights by sending a request to our email. User rights include:\n- Information about personal data processing by the controller;\n- Access to their personal data;\n- Correction of inaccurate data;\n- Deletion of personal data ("right to be forgotten");\n- Restriction of processing by the controller or processor;\n- Data portability between controllers;\n- Objection to personal data processing;\n- Right not to be subject to decisions based solely on automated processing, including profiling, which significantly affects the user;\n- Right to judicial or administrative protection if rights are violated.',
    'legal.privacy.section3.deletion': 'Users may request deletion if one or more of the following apply:\n- Personal data is no longer necessary for the collection purpose;\n- Consent is withdrawn and no other legal basis for processing exists;\n- User objects to processing and no overriding legal grounds exist;\n- Personal data was unlawfully processed;\n- Deletion is necessary to comply with legal obligations under EU or national laws;\n- Accuracy of personal data is contested (in which case, processing is restricted while verified);\n- Processing is unlawful and the user prefers restriction over deletion;\n- Data is no longer needed for processing purposes but requested for legal claims;\n- User objects pending verification regarding lawful basis priority.',
    'legal.privacy.section3.restriction': 'Users may restrict processing when:\n- Contesting accuracy, with restriction during verification;\n- Processing is unlawful but refusal to delete;\n- Data not needed for processing but required for claims;\n- Objection pending verification of lawful basis dominance.',
    'legal.privacy.section3.1.title': '3.1 Right to Object Regarding Contract Performance',
    'legal.privacy.section3.1.content': 'Users may object to processing; the controller must cease processing unless there are compelling legitimate grounds that override user rights or for legal claims. For direct marketing, processing must stop immediately upon objection.',
    'legal.privacy.section3.2.title': '3.2 Right to Object',
    'legal.privacy.section3.2.content': 'Users have the right to object to personal data processing. The controller must stop processing unless compelling legitimate grounds prevail or for legal claims. For direct marketing, processing must cease immediately.',
    'legal.privacy.section3.3.title': '3.3 Complaint to Supervisory Authority',
    'legal.privacy.section3.3.content': 'Users may file complaints about unlawful personal data processing with the Personal Data Protection Commission or competent court.',
    'legal.cookies.title': 'Cookie Policy',
    'legal.cookies.subtitle': 'Use of Cookies',
    'legal.cookies.intro': 'Cookies are small text files or packets of information stored via the internet browser on your device (computer, tablet, laptop, or mobile phone) when you visit various websites and internet pages. The primary purpose of cookies is to recognize the user upon returning to the website. Some cookies have more specific uses, such as storing user behavior on the site and facilitating the user experience on the website.',
    'legal.cookies.section1.title': '1. How Are Cookies Used on This Website?',
    'legal.cookies.section1.content': 'We use cookies primarily to enhance site usability, improve website performance, and store information about user behavior. No personal data is stored through cookies; therefore, users cannot be personally identified, and data protection laws do not apply to this information. The data collected by cookies is generally aggregated to analyze user behavior on the website, allowing us to improve site functionality, user journeys, and content. Cookies may also be used for direct marketing purposes, such as delivering electronic commercial messages to users outside the website.',
    'legal.cookies.section2.title': '2. What Types of Cookies Are Used on This Website?',
    'legal.cookies.section2.subsection1.title': '2.1 Session Cookies',
    'legal.cookies.section2.subsection1.content': 'These cookies facilitate site usage by temporarily storing information during the browser session only. Typically, they store data such as items added to a shopping cart, pages visited, and navigation paths. Session cookies do not collect information from your device and are deleted automatically when you leave the site or close your browser session.',
    'legal.cookies.section2.subsection2.title': '2.2 Persistent Cookies',
    'legal.cookies.section2.subsection2.content': 'These cookies allow us to store specific browsing information, such as analyzing site visits, how users reached the site, which pages were viewed, options selected, and navigation paths taken through the website. Tracking this information enables us to make website improvements, fix errors, and expand content. The duration of storage for persistent cookies varies depending on their specific purpose.',
    'legal.cookies.section2.subsection3.title': '2.3 Third-Party Cookies',
    'legal.cookies.section2.subsection3.content': 'The website may contain links to other websites or embedded content from third-party sites such as Facebook, Instagram, LinkedIn, and partner websites. Visiting these sites or accessing embedded content may result in third-party cookies being stored on your device. We do not control the creation or management of these cookies. We advise you to review the privacy policies and cookie management settings of these third-party sites for more information.',
    'legal.cookies.section3.title': '3. How Can You Manage Cookie Use on This Website?',
    'legal.cookies.section3.content': 'All browsers provide functionality to manage cookies via a dedicated browser folder or settings menu. You can block, delete some or all cookies, or set your preferences concerning cookie use before visiting our website. Please note that deleting or blocking cookies may negatively impact the functionality of our website and your user experience.',
    'legal.cookies.section3.subsection1.title': '3.1 Disabling or Blocking Cookies',
    'legal.cookies.section3.subsection1.content': 'Managing, disabling, or blocking cookies is controlled through your browser settings. Please be aware that fully blocking all cookies may affect the website\'s functionality, efficiency, and access to certain information.',
    'footer.terms': 'Terms & Conditions',
    'footer.privacy': 'Privacy Policy',
    'footer.cookies': 'Cookie Policy',
    'footer.copyright': '© AUTEGRY 2025. All Rights Reserved.',
  },
  bg: {
    'nav.home': 'Начало',
    'nav.about': 'За нас',
    'nav.services': 'Решения', 
    'nav.contact': 'Контакти',
    'nav.getInTouch': 'Свържете се с нас',
    'hero.mainTitle': 'Агрегираме данни, автоматизираме процеси',
    'hero.subtitle': 'и доставяме моментни справки, оптимални, скалируеми и достъпни аналитични решения.',
    'hero.businessTitle': 'За бизнеса:',
    'hero.feature1': '"Данни" актуални към момента на запитване',
    'hero.feature2': '"Автоматизация", пестяща време и ресурси',
    'hero.feature3': 'Аналитични "услуги"',
    'hero.feature4': 'Вътрешни "разработки"',
    'hero.feature5': '"Експертиза" в работата с данни и познаване на процесите',
    'hero.feature6': '"10+" PhD-та и докторанти – инженери, икономисти, ИТ',
    'hero.learnMore': 'Научи повече',
    'statistics.processAutomation': 'Степен на автоматизация на процесите',
    'statistics.businessCompanies': 'Бизнес компании, с които работим',
    'statistics.analyticalProducts': 'Аналитични продукти',
    'problems.title': 'Предизвикателства, които решаваме',
    'problems.1.title': 'Остаряла кредитна история',
    'problems.1.desc1': 'Инертността на кредитните бюра води до рисково кредитиране и измами.',
    'problems.1.feature1': 'Агрегираме данни в реално време от финансови компании и други източници',
    'problems.1.result': 'Повече одобрения при зададен риск и по-малко измами благодарение на актуалните данни',
    'problems.2.title': 'Ограничени данни → Ограничени решения',
    'problems.2.desc1': 'Вътрешните модели и стратегии зависят само от данните на клиентите на компанията.',
    'problems.2.feature1': 'Предоставяме допълващи обобщени данни и скорове',
    'problems.2.result': 'Повече одобрения при зададен риск и по-малко измами благодарение на допълнителните данни',
    'problems.3.title': 'Недостатъчно одобрения при желан риск',
    'problems.3.desc1': 'Висок риск сред одобрените и/или пропуснати ползи сред отхвърлените.',
    'problems.3.feature1': 'Предоставяме агрегирани данни в реално време от много източници',
    'problems.3.feature2': 'Доставяме генерализирани скорове базирани на обединените актуални данни',
    'problems.3.result': 'Повече одобрения при зададен риск благодарение на по-информирани решения',
    'problems.4.title': 'Отказали се одобрени кандидати',
    'problems.4.desc1': 'Бавно одобрение или неподходящи параметри на кредит.',
    'problems.4.feature1': 'Бърз отговор с агрегирани данни и скорове',
    'problems.4.feature2': 'Определяме подходящи параметри на продукта чрез анализ на данни и експертно знание',
    'problems.4.result': 'По-малко отказали се след одобрение',
    'problems.5.title': 'Риск от измами',
    'problems.5.desc1': 'Откриването на измами зависи от ограничените данни в компанията.',
    'problems.5.feature1': 'Използваме актуални и допълващи данни за измами',
    'problems.5.feature2': 'Проверяваме коректността на подадените от клиента данни',
    'problems.5.result': 'По-добра защита от измами',
    'problems.6.title': 'Неефективна събираемост',
    'problems.6.desc1': 'Неоптимално взаимодействие с активните клиенти.',
    'problems.6.feature1': 'Прогнозираме поведението на активни клиенти',
    'problems.6.feature2': 'Оценяваме платежоспособността и вероятността за събираемост',
    'problems.6.feature3': 'Формираме оптимална стратегия на индивидуално ниво',
    'problems.6.result': 'Оптимизирана събираемост на всички нива',
    'problems.7.title': 'Неефективно привличане на клиенти',
    'problems.7.desc1': 'Неоправдана цена за привличане, пропуснати или грешно таргетирани клиенти.',
    'problems.7.feature1': 'Адаптивните свойства на решението ни водят до по-точна прогноза на склонността (propensity)',
    'problems.7.result': 'По-ефективно таргетиране на клиенти',
    'problems.8.title': 'Неоптимални маркетингови кампании',
    'problems.8.desc1': 'Неоптимални параметри на индивидуални оферти. Маркетингът не е синхронен с риск, бюджет и други ограничения.',
    'problems.8.feature1': 'Разработихме система за оптимизация на индивидуални оферти',
    'problems.8.feature2': 'Адаптивните ѝ свойства водят до актуални оферти',
    'problems.8.feature3': 'Отчитаме бизнес ограниченията',
    'problems.8.result': 'Оптимално привличане на клиенти',
    'problems.9.title': 'Регулаторен риск',
    'problems.9.desc1': 'Регулаторни глоби и санкции при неспазени правила.',
    'problems.9.feature1': 'Предоставяме скоринги в съответствие с регулаторните изисквания',
    'problems.9.result': 'Избягване на регулаторни санкции',
    'services.title': 'Нашите решения',
    'services.description': 'Предоставяме: аналитични решения (SOL), обучавани върху обобщени или персонални клиентски данни, резултата (RSP) от изпълнението на решенията или завършен софтуерен продукт (ASF) за производство на SOL.',
    'services.rsp.title': 'RSP: Резултат от решение',
    'services.rsp.desc': 'скор, прогноза, оптимална препоръка, оферта и др., предоставяни в реално време или на дневна база, регулярно актуализирани, с постоянно наблюдение и поддръжка',
    'services.sol.title': 'SOL: Аналитично решение',
    'services.sol.desc': 'система за генериране на RSP, съставена от модул за: подготовка на данни, сегментация, прогнозиране, калибрация, формиране препоръки, оферти и др. Предоставя се на тримесечие, с трансформирани входни променливи, получавани по заявка, с постоянно наблюдение и поддръжка',
    'services.asf.title': 'ASF: Автоматизирана фабрика за решения',
    'services.asf.desc': 'завършен софтуерен продукт за генериране на SOL, внедряван на проектна база, с постоянно наблюдение и поддръжка',
    'services.filters.all': 'Всички',
    'services.filters.applicants': 'Кандидатстващи',
    'services.filters.activeClients': 'Активни клиенти',
    'services.filters.inactiveClients': 'Неактивни клиенти',
    'services.bureauScoring.title': 'Персонален скор на АУТЕГРИ (PAS)',
    'services.bureauScoring.desc': 'Отразява обобщено рисково поведение в агрегираните от АУТЕГРИ данни',
    'services.applicationScoring.title': 'Кандидатстване',
    'services.applicationScoring.desc': 'Оценява риска в реално време при кандидатстване',
    'services.fraudScoring.title': 'Измами',
    'services.fraudScoring.desc': 'Открива измами в реално време с използване на агрегираните от АУТЕГРИ данни',
    'services.behavioralScoring.title': 'Текущо поведение',
    'services.behavioralScoring.desc': 'Оценка на динамично променящия се риск на активни кредитополучатели',
    'services.propensityScoring.title': 'Склонност (Propensity)',
    'services.propensityScoring.desc': 'Отразява вероятността клиент да кандидатства за кредит',
    'services.churnScore.title': 'Загуба (Churn)',
    'services.churnScore.desc': 'Отразява вероятността за загуба на клиент',
    'services.collection.title': 'Събираемост (Collection)',
    'services.collection.desc': 'Оценка на риска просрочил клиент да не плати в близко бъдеще',
    'services.recovery.title': 'Възстановяване (Recovery)',
    'services.recovery.desc': 'Отразява риска от неизплащане на суми от отписани / силно просрочени кредити',
    'services.cashflow.title': 'Парични потоци',
    'services.cashflow.desc': 'Прогнози за приходи по договори',
    'services.marketing.title': 'Маркетинг',
    'services.marketing.desc': 'Постоянна оптимална кампания - настроена за една или множество цели',
    'services.features.applicationScoring.1': 'Скор 0-1000, калибриран, със стандартни зони A1-E4',
    'services.features.applicationScoring.2': 'Основните позитивни и негативни фактори',
    'services.features.applicationScoring.3': 'В съответствие с регулаторните изисквания',
    'services.features.applicationScoring.4': 'Обновяване на моделите и калибрация на всеки 3 месеца',
    'services.features.bureauScoring.1': 'Оценка на риска в реално време при кандидатстване',
    'services.features.bureauScoring.2': 'Универсален скор 0-1000, калибриран, със стандартни зони A1-E4',
    'services.features.bureauScoring.3': 'Основните позитивни и негативни фактори',
    'services.features.bureauScoring.4': 'В съответствие с регулаторните изисквания',
    'services.features.bureauScoring.5': 'Обновяване на моделите и калибрация на всеки 3 месеца',
    'services.features.fraudScoring.1': 'Обучение върху агрегираните от АУТЕГРИ данни',
    'services.features.fraudScoring.2': 'Отразява предефинирано измамно поведение в агрегираните данни в АУТЕГРИ',
    'services.features.fraudScoring.3': 'Скор 0-1000, калибриран, със стандартни зони A-E',
    'services.features.fraudScoring.4': 'Обновяване на моделите и калибрация на всеки 3 месеца',
    'services.features.behavioral.1': 'Отразява динамични промени в поведението',
    'services.features.behavioral.2': 'Скор 0-1000, калибриран, със стандартни зони A1-E4',
    'services.features.behavioral.3': 'Обновяване на моделите и калибрация на всеки 3 месеца',
    'services.features.churn.1': 'Скор 0-1000, калибриран, със стандартни зони A1-E4',
    'services.features.churn.2': 'Обновяване на моделите и калибрация на всеки 3 месеца',
    'services.features.churn.3': '',
    'services.features.collection.1': 'Скор 0-1000, калибриран, със стандартни зони A1-E4',
    'services.features.collection.2': 'Обновяване на моделите и калибрация на всеки 3 месеца',
    'services.features.recovery.1': 'Скор 0-1000, калибриран, със стандартни зони A1-E4',
    'services.features.recovery.2': 'Обновяване на моделите и калибрация на всеки 3 месеца',
    'services.features.cashflow.1': 'Хоризонти: 1, 2, 3, 6, 12 месеца',
    'services.features.cashflow.2': 'Индивидуално и агрегирано ниво',
    'services.features.cashflow.3': 'Обновяване на моделите на всеки 3 месеца',
    'services.features.marketing.1': 'Отчитане на ограничения (риск, бюджет, честота на офериране и др.)',
    'services.features.marketing.2': 'Адаптация към текущото поведение на пазара',
    'services.features.marketing.3': 'Оптимизация на индивидуално ниво',
    'services.features.marketing.4': 'AI-базирани персонални препоръки',
    'services.features.marketing.5': 'Ежедневна адаптация към поведението на клиентите',
    'about.title': 'За нас',
    'about.mission.title': 'Мисия',
    'about.mission.desc': 'Автоматизация и данни за сигурно, оптимално и изгодно управление на вашия бизнес.',
    'about.vision.title': 'Визия',
    'about.vision.desc': 'Устойчив и ефективен бизнес растеж.',
    'about.whoWeAre.title': 'Кои сме ние',
    'about.whoWeAre.desc': 'Ние сме PhD екип, който съчетава опит в работата с данни и ИТ с експертиза във финанси, търговия, маркетинг и автоматизация на индустриални процеси.',
    'insights.title': 'Блог',
    'footer.description': 'Ние агрегираме данни, автоматизираме процеси и доставяме моментни справки, както и оптимални, скалируеми и достъпни аналитични решения.',
    'footer.company': 'За компанията',
    'footer.services': 'Решения',
    'footer.getInTouch': 'Свържете се с нас',
    'footer.home': 'Начало',
    'footer.aboutUs': 'За нас',
    'footer.solutions': 'Решения',
    'footer.contact': 'Контакти',
    'whyAutegry.title': 'Защо АУТЕГРИ',
    'whyAutegry.subtitle': 'С нас достъпвате агрегирани данни, аналитични и технологични решения. С нашата автоматизация постигате оптимално управление на вашия бизнес.',
    'whyAutegry.automation.title': 'Автоматизация',
    'whyAutegry.automation.desc': 'Автоматизация на data science, бизнес и индустриални процеси за постигане на оптимални, скалируеми и икономически ефективни резултати.',
    'whyAutegry.realTimeData.title': 'Данни',
    'whyAutegry.realTimeData.desc': 'Данните са безценен ресурс. Ние непрестанно работим за увеличаване и обогатяване на данните, които събираме.',
    'whyAutegry.analytics.title': 'Аналитичност',
    'whyAutegry.analytics.desc': 'Обединявайки подхода, базиран на данни, с експертно знание, създаваме завършени аналитични решения, чрез които автоматизираме процеси.',
    'whyAutegry.technology.title': 'Технология',
    'whyAutegry.technology.desc': 'Технологията е в основата на всичко, което правим. Сигурността на системите ни е наш най-висок приоритет, а ефективността им е катализатор на качеството на услугите и разработките ни.',
    'cookieBanner.title': 'Този уебсайт използва бисквитки',
    'cookieBanner.description': 'Този сайт използва „бисквитки", за да подобри вашето преживяване. Използваме ги, за да анализираме трафика и да персонализираме съдържанието специално за вас. Продължавайки да разглеждате, вие се съгласявате с нашата Политика за бисквитки',
    'cookieBanner.allowAll': 'Разреши всички',
    'cookieBanner.necessary': 'Разреши само необходимите',
    'contact.title': 'Изпратете ни съобщение',
    'contact.name': 'Пълно име',
    'contact.namePlaceholder': 'Jane Doe',
    'contact.email': 'Служебен имейл',
    'contact.emailPlaceholder': 'example@domain.com',
    'contact.phone': 'Мобилен телефон',
    'contact.phonePlaceholder': '+359 ..',
    'contact.subject': 'ТЕМА',
    'contact.subjectPlaceholder': 'Въведете тема',
    'contact.message': 'СЪОБЩЕНИЕ',
    'contact.messagePlaceholder': 'Моля, напишете вашето съобщение',
    'contact.submit': 'Изпратете съобщение',
    'contact.contactUs': 'СВЪРЖЕТЕ СЕ С НАС',
    'contact.emailLabel': 'ИМЕЙЛ',
    'contact.phoneLabel': 'ТЕЛЕФОН',
    'contact.officeLabel': 'АДРЕС',
    'contact.socialLabel': 'СОЦИАЛНИ МРЕЖИ',
    'contact.officeAddress': 'София, 1756, ж.к. Студентски град, ул. „Росарио" 1',
    'team.title': 'Нашият екип',
    'team.subtitle': 'Запознайте се с експертите, които правят възможни нашите решения',
    'team.connect': 'Свържете се',
    'services.loadMore': 'Покажи повече',
    'services.showLess': 'Скрий',
    'team.member1.name': 'Александър Ефремов',
    'team.member1.position': 'Управител и Основател',
    'team.member1.email': 'alexander.efremov@autegry.com',
    'team.member1.bio': '25+ години опит в Data Science, автоматизация, адаптивни системи и приложен AI в химическата индустрия, спътниковата комуникация, ритейла, кредитирането, маркетинга и др. Доцент и зам.-декан по Бизнес отношения във Факултет Автоматика на ТУ–София, където води курсове по ML, DM, AI, Автоматизация на производството и др.',
    'team.member1.linkedin': 'linkedin.com/in/aefremov',
    'team.member2.name': 'Фани Томова',
    'team.member2.position': 'Главен архитект Бази Данни и Хранилища',
    'team.member2.email': 'fani.tomova@autegry.com',
    'team.member2.bio': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.',
    'team.member2.linkedin': 'linkedin.com/in/lorem-ipsum',
    'team.member3.name': 'Радостин Мераков',
    'team.member3.position': 'Главен Архитект Платформени Системи',
    'team.member3.email': 'radostin.merakov@autegry.com',
    'team.member3.bio': 'Дългогодишен опит в Python разработката, DevOps практиките и проектирането на бази данни. Специализиран в изграждането на мащабируеми системи със SQLAlchemy и Alembic и в ръководенето на платформени операции за надеждни и поддържани приложения.',
    'team.member3.linkedin': 'linkedin.com/in/lorem-ipsum',
    'team.member4.name': 'Ивета Григорова',
    'team.member4.position': 'Ръководител Аналитични Решения и Внедряване',
    'team.member4.email': 'iveta.grigorova@autegry.com',
    'team.member4.bio': 'С богат опит в Data Science, финансов контрол, вътрешен одит и счетоводство. Докторант във Факултета по Автоматика на ТУ - София и преподавател по ML, DM и AI в ТУ - София и ПУ „Паисий Хилендарски". Отговаря за бизнес частта по разработването и доставката на решения RSP, SOL и ASF. Координира ключови процеси, настройва и администрира ASF, анализира отчети и осъществява мониторинг от гледна точка на Data Science. Управлява комуникацията с клиенти, извършва бизнес анализи и представя резултатите на различни нива.',
    'team.member4.linkedin': 'linkedin.com/in/lorem-ipsum',
    'team.member5.name': 'Александър Карамфилов',
    'team.member5.position': 'Ръководител Стратегически Проекти',
    'team.member5.email': 'alexander.karamfilov@autegry.com',
    'team.member5.bio': 'Ръководи техническата разработка на ASF системи, координира екипи в областта на Data Science, осъществява ефективна комуникация с клиентите, представя бизнес анализ и резултати, както и организира интеграцията на решенията в сътрудничество с различни екипи. Той следи изпълнението на проектите, решава технически и организационни предизвикателства и осигурява качествена доставка на продуктите съгласно изискванията.',
    'team.member5.linkedin': 'linkedin.com/in/lorem-ipsum',
    'team.member6.name': 'Нелина Неделчева',
    'team.member6.position': 'Ръководител Дизайн и Маркетинг',
    'team.member6.email': 'nelina.nedelcheva@autegry.com',
    'team.member6.bio': 'Управлява цялостната визуална идентичност и маркетингови кампании, създава ефективни дизайн стратегии, координира екипи и анализира пазарни тенденции за оптимизиране на бранда. Завършила е „Дизайн и печатни комуникации" в Технически университет - София, филиал Пловдив.',
    'team.member6.linkedin': 'linkedin.com/in/lorem-ipsum',
    'legal.title': 'Правна информация',
    'legal.subtitle': 'Важна информация за нашите условия, практики за поверителност и използване на бисквитки',
    'legal.terms.title': 'Общи условия',
    'legal.terms.intro': 'Нашето дружество – Аутегри ЕООД, регистрирано в българския Търговски регистър при Агенцията по вписванията, с ЕИК: 206957397, със седалище и адрес на управление: Република България, София, 1756, ж.к. Студентски град, ул. „Росарио" 1, телефон: +359 89 999 9999, електронна поща: info@autegry.com. Настоящите общи условия уреждат условията за използване на www.autegry.com. Чрез използването на уебсайта потребителят се съгласява с настоящите общи условия. Ако не сте съгласни със същите, следва да се въздържате от използване на уебсайта.',
    'legal.terms.section1.title': '1. Интелектуална собственост',
    'legal.terms.section1.p1': '1.1 Всички права върху интелектуалната собственост по отношение на информационните ресурси и съдържанието на уебсайта се упражняват от Оператора. Същите са защитени от Закона за авторското право и сродните му права и всяко използване на съдържание от Уебсайта без съгласието на Оператора е нарушение на закона, от което може да последва гражданска, административно наказателна или наказателна отговорност.',
    'legal.terms.section1.p2': '1.2 При копиране или възпроизвеждане на информация вън от допустимото, както и при всяко друго нарушение на правата на интелектуална собственост върху ресурсите на Оператора, Операторът има правото да претендира обезщетение и за претърпените преки и косвени вреди в пълен размер.',
    'legal.terms.section2.title': '2. Ограничаване на отговорността',
    'legal.terms.section2.p1': '2.1 Операторът предприема необходимите мерки, за да поддържа съдържанието на уебсайта актуално, но не носи отговорност за действителната актуалност на същото. Във връзка с това операторът не носи отговорност за вреди, в това число преки и косвени вреди, включително пропуснати ползи, които потребител на уебсайта би понесъл при каквито и да е обстоятелства, свързани с публикуваното съдържание на уебсайта и достъпа до същия. Използвайки уебсайта, потребителите поемат всички рискове, свързани с това, включително всеки риск за крайни потребителски устройства, софтуер или данни на потребителите.',
    'legal.terms.section2.p2': '2.2 Доколкото в съдържанието на уебсайта се съдържат препратки към съдържание, позиционирано извън същия потребителят е запознат с факта, че операторът няма контрол върху същото и не носи отговорност за последиците от активиране на препратки, водещи извън уебсайта. Операторът не носи отговорност за злонамерни действия от страна на трети лица, обект на които би могъл да стане потребителя, при използване на уебсайта. Потребителят използва уебсайта на своя отговорност.',
    'legal.terms.section3.title': '3. Регистрация на потребители',
    'legal.terms.section3.p1': '3.1 Операторът запазва правото си да предоставя част от съдържанието на уебсайта единствено на потребители, които са регистрирали свой потребителски профил на уебсайта. Съответното съдържание, ограничено единствено до регистрирани потребители, следва във всеки един момент да бъде обозначено като такова от страна на оператора.',
    'legal.terms.section3.p2': '3.2 При създаване на потребителски профил потребителят се съгласява, че операторът ще обработва неговите лични данни съобразно с правилата на Политиката за защита на лични данни, публикувана на уебсайта.',
    'legal.terms.section4.title': '4. Използване на уебсайта',
    'legal.terms.section4.p1': '4.1 Доколкото операторът е предвидил възможност за потребители да качват съдържание в уебсайта, същите следва да не качват клеветническо, нецензурирано, обидно, порнографско или по друг начин незаконно или противоречащо на морала съдържание.',
    'legal.terms.section4.p2': '4.2 Потребителите следва да използват уебсайта добросъвестно, в това число да не предприемат злонамерени действия, които да могат да се отразят на достъпността на съдържанието за трети лица или използването на уебсайта изобщо.',
    'legal.terms.section5.title': '5. Други',
    'legal.terms.section5.p1': '5.1 Операторът запазва правото си да изменя настоящите общи условия по свое усмотрение като във всеки един момент актуалните условия за ползване на уебсайта ще бъдат публикувани на същия.',
    'legal.terms.section5.p2': '5.2 По всички неуредени от настоящите Общи условия въпроси се прилагат разпоредбите на действащото законодателство на Република България.',
    'legal.privacy.title': 'Политика за поверителност',
    'legal.privacy.subtitle': 'Полагаме грижа за личните ви данни',
    'legal.privacy.intro': 'Информация за администратора на лични данни\nАутегри ЕООД е дружество, регистрирано в Търговския регистър на Агенцията по вписванията с ЕИК: 206957397, e-mail: info@autegry.com, с тел.: +359 89 999 9999.',
    'legal.privacy.section1.title': '1. Основания и цели, за които използваме вашите лични данни',
    'legal.privacy.section1.intro': 'Ние обработваме вашите лични данни на следните основания:\nОбщите условия за използване на уебсайта;\nИзрично съгласие от вас – целта се посочва за всеки конкретен случай;\nПри предвидено задължение по закон;\nВ следващите параграфи ще намерите детайлна информация относно обработването на личните ви данни в зависимост от основанието, на което ги обработваме.',
    'legal.privacy.section1.1.title': '1.1 За изпълнение на договор',
    'legal.privacy.section1.1.content': 'Ние обработваме личните ви данни за нуждите на използване на уебсайта съобразно с правилата на общите условия.\nЦели на обработката (когато е относимо):\nустановяване на самоличността ви;\nпредоставяне на функционалностите на нашия уебсайт;\nНа това основание обработваме единствено лични данни предоставени във връзка с подаденото запитване в контактната форма, като булстат на компанията, име и фамилия, телефон и имейл адрес. Данните, събрани на това основание изтриваме 2 години след прекратяване на договорното отношение, независимо дали поради изтичане срока на договора, разваляне или друго основание.',
    'legal.privacy.section1.2.title': '1.2 След ваше съгласие',
    'legal.privacy.section1.2.content': 'Ние обработваме вашите лични данни на това основание само след изрично, недвусмислено и доброволно съгласие от ваша страна. Ние няма да предвиждаме каквито и да е неблагоприятни последици за вас, ако откажете обработването на личните данни.\nСъгласието е отделно основание за обработване на личните ви данни и целта на обработката е посочена в него, и не се покрива с целите, изброени в тази политика. Ако ни дадете съответното съгласие и до неговото оттегляне или прекратяване на всякакви договорни отношения с вас изготвяме подходящи за вас предложения за продукти/услуги, като извършваме детайлни анализи на ваши основни лични данни.\nДанни, които обработваме на това основание:\nНа това основание можем да обработваме лични данни за целите на директния маркетинг, включително данни за потребление на уебсайта и данни за профили в социалните мрежи.\nПредоставяне на данни на трети лица:\nНа това основание можем да предоставим вашите данни на маркетинг агенции, Facebook, Google или други подобни.\nОттегляне на съгласие\nПредоставените съгласия могат да бъдат оттеглени по всяко време. Оттеглянето на съгласието няма отражение върху изпълнението на договорните задължения. Ако оттеглите съгласието си за обработване на лични данни за някой или всички начини, описани по-горе, ние няма да използваме личните ви данни и информация за определените по-горе цели. Оттеглянето на съгласието не засяга законосъобразността на обработването, основано на дадено съгласие преди неговото оттегляне. За да оттеглите даденото съгласие е необходимо само да използвате сайта ни или просто данните ни за контакт.\nКога заличаваме данните, събрани на това основание\nДанните, събрани на това основание, изтриваме при искане от ваша страна или 12 месеца след първоначалното им събиране.',
    'legal.privacy.section2.title': '2. Как защитаваме вашите лични данни',
    'legal.privacy.section2.content': 'За осигуряване на адекватна защита на данните на компанията и своите клиенти, ние прилагаме всички необходими организационни и технически мерки, предвидени в Закона за защита на личните данни. Компанията е установила правила за предотвратяване на злоупотреби и пробиви в сигурността, което подпомага процесите по опазване и обезпечаване сигурността на вашите данни. С цел максимална сигурност при обработка, пренос и съхранение на вашите данни, може да използваме допълнителни механизми за защита като криптиране, псевдонимизация и др.',
    'legal.privacy.section3.title': '3. Права на потребителите',
    'legal.privacy.section3.intro': 'Всеки потребител на сайта се ползва с всички права за защита на личните данни съгласно българското законодателство и правото на Европейския съюз. Потребителят може да упражни правата си чрез изпращане на съобщение до имейла ни. Всеки потребител има право на:\nИнформираност (във връзка с обработването на личните му данни от администратора);\nДостъп до собствените си лични данни;\nКоригиране (ако данните са неточни);\nИзтриване на личните данни (право „да бъдеш забравен");\nОграничаване на обработването от страна на администратора или обработващия лични данни;\nПреносимост на личните данни между отделните администратори;\nВъзражение спрямо обработването на негови лични данни;\nСубектът на данни има право и да не бъде обект на решение, основаващо се единствено на автоматизирано обработване, включващо профилиране, което поражда правни последствия за субекта на данните или по подобен начин го засяга в значителна степен;\nПраво на защита по съдебен или административен ред, в случай, че правата на субекта на данни са били нарушени.',
    'legal.privacy.section3.deletion': 'Потребителят може да поиска изтриване, ако е налице едно от следните условия:\nЛичните данни повече не са необходими за целите, за които са били събрани или обработвани по друг начин;\nПотребителят оттегля своето съгласие, върху което се основава обработването на данните и няма друго правно основание за обработването;\nПотребителят данните възразява срещу обработването и няма законни основания за обработването, които да имат преимущество;\nЛичните данни са били обработвани незаконосъобразно;\nЛичните данни трябва да бъдат изтрити с цел спазването на правно задължение по правото на Съюза или правото на държава членка, което се прилага спрямо администратора;\nОспори точността на личните данни. В този случай ограничаването на обработването е за срок, който позволява на администратора да провери точността на личните данни;\nОбработването е неправомерно, но потребителят не желае личните данни да бъдат изтрити, а изисква вместо това ограничаване на използването им;\nАдминистраторът не се нуждае повече от личните данни за целите на обработването, но потребителят ги изисква за установяването, упражняването или защитата на правни претенции;\nВъзразява срещу обработването в очакване на проверка дали законните основания на администратора имат преимущество пред интересите на потребителя.',
    'legal.privacy.section3.restriction': 'Потребителят има право да ограничи обработването на своите лични данни от страна на администратора, когато:\nОспори точността на личните данни. В този случай ограничаването на обработването е за срок, който позволява на администратора да провери точността на личните данни;\nОбработването е неправомерно, но потребителят не желае личните данни да бъдат изтрити, а изисква вместо това ограничаване на използването им;\nАдминистраторът не се нуждае повече от личните данни за целите на обработването, но потребителят ги изисква за установяването, упражняването или защитата на правни претенции;\nВъзразява срещу обработването в очакване на проверка дали законните основания на администратора имат преимущество пред интересите на потребителя.',
    'legal.privacy.section3.1.title': '3.1 За изпълнение на договор',
    'legal.privacy.section3.1.content': 'Потребителите имат право да възразят пред администратора срещу обработването на личните им данни. Администраторът на лични данни е длъжен да прекрати обработването, освен ако не докаже, че съществуват убедителни законови основания за обработването, които имат предимство пред интересите, правата и свободите на субекта на данни, или за установяването, упражняването или защитата на правни претенции. При възразяване срещу обработването на лични данни за целите на директния маркетинг обработването следва да се прекрати незабавно.',
    'legal.privacy.section3.2.title': '3.2 Право на възражение',
    'legal.privacy.section3.2.content': 'Потребителите имат право да възразят пред администратора срещу обработването на личните им данни. Администраторът на лични данни е длъжен да прекрати обработването, освен ако не докаже, че съществуват убедителни законови основания за обработването, които имат предимство пред интересите, правата и свободите на субекта на данни, или за установяването, упражняването или защитата на правни претенции. При възразяване срещу обработването на лични данни за целите на директния маркетинг обработването следва да се прекрати незабавно.',
    'legal.privacy.section3.3.title': '3.3 Жалба до надзорния орган',
    'legal.privacy.section3.3.content': 'Всеки потребител има право да подаде жалба срещу незаконосъобразно обработване на личните му данни до Комисия за защита на личните данни или до компетентния съд.',
    'legal.cookies.title': 'Бисквитки',
    'legal.cookies.subtitle': 'Използване на „бисквитки"',
    'legal.cookies.intro': '„Бисквитките" са кратки текстови файлове или малки пакети от информация, които се съхраняват чрез интернет браузъра на вашето крайно устройство (компютър, таблет, лаптоп или мобилен телефон), когато посещавате различни сайтове и страници в интернет. Основната цел на „бисквитките" е да правят потребителя разпознаваем, когато той се завръща отново на уебсайта. Някои „бисквитки" имат и по-специфично приложение, като например да запаметяват потребителското поведение на сайта и да улесняват потребителя при ползването на уебсайта.',
    'legal.cookies.section1.title': '1. Как се използват „бисквитки" на този уебсайт?',
    'legal.cookies.section1.content': 'Ние използваме „бисквитки" на този Уебсайт предимно с цел улесняване на ползваемостта на сайта, подобряване на неговата работа и съхраняване на информация за потребителското поведение. При този процес не се съхраняват никакви лични данни, т.е. чрез "бисквитките" на сайта не може да Ви идентифицираме като личност, поради което спрямо събирането на тази информация не се прилага Закона за защита на личните данни. Събраната информация от „бисквитки" обикновено се използва в обобщен вид с цел анализ на потребителското поведение на Уебсайта, което ни позволява да подобряваме функционалността на сайта, потребителските пътеки и ползваното съдържание. Възможно е бисквитки да бъдат използвани и за целите на директния маркетинг, а именно за представяне на електронни търговски съобщения към потребителя извън Уебсайта.',
    'legal.cookies.section2.title': '2. Какви „бисквитки" се използват на този уебсайт?',
    'legal.cookies.section2.subsection1.title': '2.1 Сесийни „бисквитки"',
    'legal.cookies.section2.subsection1.content': 'Този тип „бисквитки" ви улеснява в ползването на сайта, като те съхраняват информация временно, само в рамките на сесията на използвания браузер. Обикновено информацията, която се съхранява чрез тях, е какви стоки или услуги сте добавили в количката, кои страници на сайта сте посетили и как сте стигнали до дадена информация. Тези „бисквитки" не събират информация от вашето крайно устройство и се изтриват автоматично, когато напуснете уебсайта или прекратите сесията на вашия браузър.',
    'legal.cookies.section2.subsection2.title': '2.2 Постоянни "бисквитки"',
    'legal.cookies.section2.subsection2.content': 'Те ни дават възможност да съхраняваме конкретна информация за сърфирането, като например анализиране посещенията на сайта, каквие сте достигнали до уебсайта, какви страници сте прегледали, какви опции сте избрали, както и накъде сте се насочили през този уебсайт. Проследяването на тази информация, ни дава възможност да правим подобрения на уебсайта, включително да коригираме грешки и да разширяваме съдържанието. Срокът на съхранение на този вид "бисквитки" варира според конкретното им предназначение.',
    'legal.cookies.section2.subsection3.title': '2.3 "Бисквитки" на трета страна',
    'legal.cookies.section2.subsection3.content': 'Възможно е на уебсайта да има препратки към други сайтове или вградено съдържание от други сайтове, например от Facebook, Instagram, LinkedIn, уебсайтове на партньори. Възможно е при посещаването на тези сайтове или отварянето на съдържанието от тях, да се складират на Вашето крайно устройство „бисквитки" от тези уебсайтове. Именно тези „бисквитки" се дефинират като „бисквитки на трети страни", като нямаме контрол върху генерирането и управлението на тези „бисквитки". За това Ви съветваме да потърсите информация за тях и за начина им на управление на уебсайтовете на съответните трети страни.',
    'legal.cookies.section3.title': '3. Как мога да управлявам използването на „бисквитки" от този уебсайт?',
    'legal.cookies.section3.content': 'Всички браузъри позволяват управлението на „бисквитки" от специално създадена за целта папка на вашия браузър. Можете да блокирате получаването на „бисквитки", да изтриете всички или част от тях или да зададете Вашите настройки за предпочитания по отношение на използването на „бисквитки" преди да инициирате посещение на сайта ни. Имайте предвид, че изтриването или блокирането на „бисквитки" може да повлияе неблагоприятно върху функциите на нашия уебсайт, а оттам и върху вашето потребителско преживяване на него.',
    'legal.cookies.section3.subsection1.title': '3.1 Изключване или блокиране на „бисквитки"',
    'legal.cookies.section3.subsection1.content': 'Контролирането, изключването или блокирането на „бисквитките" се управлява от настройките на вашия браузер. Имайте предвид, че пълната забрана на използването на всички „бисквитки", може да рефлектира върху функционалното представяне на сайта, неговата ефективност и достъпването на определена информация.',
    'footer.terms': 'Общи условия',
    'footer.privacy': 'Политика за поверителност',
    'footer.cookies': 'Бисквитки',
    'footer.copyright': '© AUTEGRY 2025. Всички права запазени.',
  },
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('bg');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};